;	DO NOT EDIT THIS FILE!!!!
;	DO NOT EDIT THIS FILE!!!!
;	DO NOT EDIT THIS FILE!!!!
;	DO NOT EDIT THIS FILE!!!!
;	DO NOT EDIT THIS FILE!!!!

	AREA project, CODE, READONLY
	EXPORT	covert

;	R7 is (will be) the decryption key
;	R0 contains the encrypted message when LED2 is on
;	R0 LSB contains 1 bit of the key whenever LED4 is on (MSB to LSB)

covert	PROC
	MOV32	R1, #0x2009C038
	
	MOV32	R0, #0x3a97afb1
	MOV		R2, #0x00100000
	BL		transmit


	MOV32	R0, #0xc21b3e36
	MOV		R2, #0x00800000
	BL		transmit


	MOV32	R0, #0x528abbdc
	MOV		R2, #0x00100000
	BL		transmit


	MOV32	R0, #0xb42933c
	MOV		R2, #0x00200000
	BL		transmit


	MOV32	R0, #0xc58bf76f
	MOV		R2, #0x00200000
	BL		transmit


	MOV32	R0, #0x6b2c2be2
	MOV		R2, #0x00040000
	BL		transmit


	MOV32	R0, #0x5ee2a6c8
	MOV		R2, #0x00100000
	BL		transmit


	MOV32	R0, #0x7fef5d99
	MOV		R2, #0x00200000
	BL		transmit


	MOV32	R0, #0x876e899b
	MOV		R2, #0x00040000
	BL		transmit


	MOV32	R0, #0x667177ca
	MOV		R2, #0x00200000
	BL		transmit


	MOV32	R0, #0xcf5a2b37
	MOV		R2, #0x00800000
	BL		transmit


	MOV32	R0, #0x15354403
	MOV		R2, #0x00800000
	BL		transmit


	MOV32	R0, #0x33e3ceca
	MOV		R2, #0x00100000
	BL		transmit


	MOV32	R0, #0x17e299f4
	MOV		R2, #0x00100000
	BL		transmit


	MOV32	R0, #0xd26ad6f9
	MOV		R2, #0x00800000
	BL		transmit


	MOV32	R0, #0xca01fd08
	MOV		R2, #0x00800000
	BL		transmit


	MOV32	R0, #0x1eaecef6
	MOV		R2, #0x00100000
	BL		transmit


	MOV32	R0, #0xa35e98c4
	MOV		R2, #0x00800000
	BL		transmit


	MOV32	R0, #0xb6dda1d4
	MOV		R2, #0x00200000
	BL		transmit


	MOV32	R0, #0x1ba680fc
	MOV		R2, #0x00100000
	BL		transmit


	MOV32	R0, #0xb2de585e
	MOV		R2, #0x00040000
	BL		transmit


	MOV32	R0, #0x3ca9d52c
	MOV		R2, #0x00200000
	BL		transmit


	MOV32	R0, #0xe3fd487f
	MOV		R2, #0x00200000
	BL		transmit


	MOV32	R0, #0x29a60741
	MOV		R2, #0x00800000
	BL		transmit


	MOV32	R0, #0x4e87e54c
	MOV		R2, #0x00800000
	BL		transmit


	MOV32	R0, #0x6516d79
	MOV		R2, #0x00200000
	BL		transmit


	MOV32	R0, #0x9ed488cd
	MOV		R2, #0x00040000
	BL		transmit


	MOV32	R0, #0x9408ef23
	MOV		R2, #0x00800000
	BL		transmit


	MOV32	R0, #0x7dbde902
	MOV		R2, #0x00200000
	BL		transmit


	MOV32	R0, #0xd6462ad1
	MOV		R2, #0x00200000
	BL		transmit


	MOV32	R0, #0x2e2acf4
	MOV		R2, #0x00100000
	BL		transmit


	MOV32	R0, #0x5d815c65
	MOV		R2, #0x00040000
	BL		transmit


	MOV32	R0, #0x3ef718dc
	MOV		R2, #0x00040000
	BL		transmit


	MOV32	R0, #0xe0451480
	MOV		R2, #0x00040000
	BL		transmit


	MOV32	R0, #0x20be40d5
	MOV		R2, #0x00800000
	BL		transmit


	MOV32	R0, #0x69a9cf4a
	MOV		R2, #0x00800000
	BL		transmit


	MOV32	R0, #0x537f18d8
	MOV		R2, #0x00200000
	BL		transmit


	MOV32	R0, #0xa2f64aa4
	MOV		R2, #0x00040000
	BL		transmit


	MOV32	R0, #0x438228b4
	MOV		R2, #0x00040000
	BL		transmit


	MOV32	R0, #0x50b004db
	MOV		R2, #0x00040000
	BL		transmit


	MOV32	R0, #0x1eaecee9
	MOV		R2, #0x00100000
	BL		transmit


	MOV32	R0, #0x5b5a7143
	MOV		R2, #0x00040000
	BL		transmit


	MOV32	R0, #0x1aa7ceda
	MOV		R2, #0x00100000
	BL		transmit


	MOV32	R0, #0xf666ab7d
	MOV		R2, #0x00040000
	BL		transmit


	MOV32	R0, #0x958e80c3
	MOV		R2, #0x00040000
	BL		transmit


	MOV32	R0, #0x85ede754
	MOV		R2, #0x00800000
	BL		transmit


	MOV32	R0, #0x3317c1f2
	MOV		R2, #0x00800000
	BL		transmit


	MOV32	R0, #0x3876fe95
	MOV		R2, #0x00200000
	BL		transmit


	MOV32	R0, #0x1da39abd
	MOV		R2, #0x00100000
	BL		transmit


	MOV32	R0, #0x2168a352
	MOV		R2, #0x00800000
	BL		transmit


	MOV32	R0, #0x260aef21
	MOV		R2, #0x00800000
	BL		transmit


	MOV32	R0, #0x7f0448a
	MOV		R2, #0x00800000
	BL		transmit


	MOV32	R0, #0x1daccedb
	MOV		R2, #0x00100000
	BL		transmit


	MOV32	R0, #0xcea46caa
	MOV		R2, #0x00040000
	BL		transmit


	MOV32	R0, #0x2541d075
	MOV		R2, #0x00800000
	BL		transmit


	MOV32	R0, #0xe7b94803
	MOV		R2, #0x00200000
	BL		transmit


	MOV32	R0, #0x76734823
	MOV		R2, #0x00800000
	BL		transmit


	MOV32	R0, #0xab8afc
	MOV		R2, #0x00100000
	BL		transmit


	MOV32	R0, #0xb6404950
	MOV		R2, #0x00040000
	BL		transmit


	MOV32	R0, #0xbe280f4
	MOV		R2, #0x00100000
	BL		transmit


	MOV32	R0, #0xc15eb136
	MOV		R2, #0x00200000
	BL		transmit


	MOV32	R0, #0xcff32ad1
	MOV		R2, #0x00800000
	BL		transmit


	MOV32	R0, #0x18ae8079
	MOV		R2, #0x00200000
	BL		transmit


	MOV32	R0, #0x585c380e
	MOV		R2, #0x00800000
	BL		transmit


	MOV32	R0, #0xccdc03e4
	MOV		R2, #0x00200000
	BL		transmit


	MOV32	R0, #0xe79089dd
	MOV		R2, #0x00200000
	BL		transmit


	MOV32	R0, #0x85a5dce9
	MOV		R2, #0x00200000
	BL		transmit


	MOV32	R0, #0x73e226cd
	MOV		R2, #0x00040000
	BL		transmit


	MOV32	R0, #0x15aa9abd
	MOV		R2, #0x00100000
	BL		transmit


	MOV32	R0, #0x74c14e85
	MOV		R2, #0x00040000
	BL		transmit


	MOV32	R0, #0x9896b2e8
	MOV		R2, #0x00040000
	BL		transmit


	MOV32	R0, #0x32e2dcac
	MOV		R2, #0x00100000
	BL		transmit


	MOV32	R0, #0x36333ec1
	MOV		R2, #0x00800000
	BL		transmit


	MOV32	R0, #0x42f2cefc
	MOV		R2, #0x00100000
	BL		transmit


	MOV32	R0, #0x81d69c43
	MOV		R2, #0x00800000
	BL		transmit


	MOV32	R0, #0x7834ff7e
	MOV		R2, #0x00040000
	BL		transmit


	MOV32	R0, #0xee6d462f
	MOV		R2, #0x00040000
	BL		transmit


	MOV32	R0, #0x212a865
	MOV		R2, #0x00800000
	BL		transmit


	MOV32	R0, #0xe6dfc977
	MOV		R2, #0x00200000
	BL		transmit


	MOV32	R0, #0x798b3a32
	MOV		R2, #0x00040000
	BL		transmit


	MOV32	R0, #0x842f09df
	MOV		R2, #0x00040000
	BL		transmit


	MOV32	R0, #0xfd891162
	MOV		R2, #0x00800000
	BL		transmit


	MOV32	R0, #0x1e286f8
	MOV		R2, #0x00100000
	BL		transmit


	MOV32	R0, #0x8c257861
	MOV		R2, #0x00200000
	BL		transmit


	MOV32	R0, #0xdcd469d3
	MOV		R2, #0x00200000
	BL		transmit


	MOV32	R0, #0xcb10bec9
	MOV		R2, #0x00800000
	BL		transmit


	MOV32	R0, #0x52ab9dbd
	MOV		R2, #0x00100000
	BL		transmit


	MOV32	R0, #0xa0569992
	MOV		R2, #0x00800000
	BL		transmit


	MOV32	R0, #0x4f4ff3ea
	MOV		R2, #0x00040000
	BL		transmit


	MOV32	R0, #0x5974c3aa
	MOV		R2, #0x00200000
	BL		transmit


	MOV32	R0, #0x17b18df2
	MOV		R2, #0x00100000
	BL		transmit


	MOV32	R0, #0xb68bf9
	MOV		R2, #0x00100000
	BL		transmit


	MOV32	R0, #0x2c026a1a
	MOV		R2, #0x00040000
	BL		transmit


	MOV32	R0, #0x85dbd460
	MOV		R2, #0x00800000
	BL		transmit


	MOV32	R0, #0x465a049b
	MOV		R2, #0x00800000
	BL		transmit


	MOV32	R0, #0x52ad9be9
	MOV		R2, #0x00100000
	BL		transmit


	MOV32	R0, #0xc1843824
	MOV		R2, #0x00040000
	BL		transmit


	MOV32	R0, #0xe5d591f9
	MOV		R2, #0x00040000
	BL		transmit


	MOV32	R0, #0xe76a25fe
	MOV		R2, #0x00200000
	BL		transmit


	MOV32	R0, #0x31a4fb79
	MOV		R2, #0x00200000
	BL		transmit


	MOV32	R0, #0x52ad88bd
	MOV		R2, #0x00100000
	BL		transmit


	MOV32	R0, #0x699e1e
	MOV		R2, #0x00040000
	BL		transmit


	MOV32	R0, #0x6b0e9031
	MOV		R2, #0x00040000
	BL		transmit


	MOV32	R0, #0x2f0b741f
	MOV		R2, #0x00800000
	BL		transmit


	MOV32	R0, #0x5e0ba7ee
	MOV		R2, #0x00200000
	BL		transmit


	MOV32	R0, #0x2791a0dc
	MOV		R2, #0x00100000
	BL		transmit


	MOV32	R0, #0x52b686ef
	MOV		R2, #0x00100000
	BL		transmit


	MOV32	R0, #0xac27a375
	MOV		R2, #0x00200000
	BL		transmit


	MOV32	R0, #0x82d240ab
	MOV		R2, #0x00040000
	BL		transmit


	MOV32	R0, #0x1db789f5
	MOV		R2, #0x00100000
	BL		transmit


	MOV32	R0, #0xbdc952a2
	MOV		R2, #0x00200000
	BL		transmit


	MOV32	R0, #0x1cdf1f15
	MOV		R2, #0x00200000
	BL		transmit


	MOV32	R0, #0xab386ec3
	MOV		R2, #0x00800000
	BL		transmit


	MOV32	R0, #0x52858fe9
	MOV		R2, #0x00100000
	BL		transmit


	MOV32	R0, #0x27da3605
	MOV		R2, #0x00040000
	BL		transmit


	MOV32	R0, #0xcebb7b66
	MOV		R2, #0x00800000
	BL		transmit


	MOV32	R0, #0x6572e3c2
	MOV		R2, #0x00040000
	BL		transmit


	MOV32	R0, #0x17e2ddb3
	MOV		R2, #0x00100000
	BL		transmit


	MOV32	R0, #0x5c4fe5df
	MOV		R2, #0x00800000
	BL		transmit


	MOV32	R0, #0x528abbdc
	MOV		R2, #0x00100000
	BL		transmit


	MOV32	R0, #0xbe7edd46
	MOV		R2, #0x00040000
	BL		transmit


	MOV32	R0, #0x5ee2a6c8
	MOV		R2, #0x00100000
	BL		transmit


	MOV32	R0, #0x33eeced5
	MOV		R2, #0x00100000
	BL		transmit


	MOV32	R0, #0x2783cfbc
	MOV		R2, #0x00100000
	BL		transmit


	MOV32	R0, #0x51a85567
	MOV		R2, #0x00200000
	BL		transmit


	MOV32	R0, #0x6545a3bd
	MOV		R2, #0x00200000
	BL		transmit


	MOV32	R0, #0x9c7f6c8e
	MOV		R2, #0x00200000
	BL		transmit


	MOV32	R0, #0x24ebafaf
	MOV		R2, #0x00200000
	BL		transmit
	
	;B		covert
	BX		LR					; Finished, Infinite loop
	ENDP

transmit	PROC
	EOR		R0, R7				; Decrypt the message
	STR		R2, [R1, #0]		; Turn on LED
	; Check message value here
	STR		R2, [R1, #4]		; Turn off LED
	
	BX		LR
	ENDP
	END